version: '3'

services:
  irisnode0:
    container_name: iritanode0
    image: bianjieai/irita:latest
    ports:
    - "26656-26657:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/nodecluster/node0 && irita start --home irita'
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  irisnode1:
    container_name: iritanode1
    image: bianjieai/irita:latest
    ports:
    - "26659-26660:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/nodecluster/node1 && irita start --home irita'
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  irisnode2:
    container_name: iritanode2
    image: bianjieai/irita:latest
    ports:
    - "26661-26662:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/nodecluster/node2 && irita start --home irita'
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  irisnode3:
    container_name: iritanode3
    image: bianjieai/irita:latest
    ports:
    - "26663-26664:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/nodecluster/node3 && irita start --home irita'
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/16
